### ISSUE TITLE
Crash on startup caused by ITLT

### ISSUE THREAD

**Issue by Kingcardien** [Spudstak/Dimensions-Dungeoneering#2]
The game crash on startup with the pack version "Dimensions and Dungeoneering-0.15.zip"
The error is 
> java.lang.NullPointerException: Registry Object not present: conjuring:soul_alloy_sword

but when removing the conjurer file, the error is :

> Mod File: itlt-1.16.x-2.0.0.jar
> Failure message: It's The Little Things (itlt) has failed to load correctly
> 	java.lang.ExceptionInInitializerError: null
> Mod Version: 2.0.0
> Mod Issue URL: https://github.com/zlepper/itlt/issues
> Exception message: java.lang.NumberFormatException: For input string: "7,1"

Changing the conjuring mod version lead to the same first crash report.
Removing the itlt file seems to resolve the problem.
I am using the GDLauncher v1.1.11 with java 1.8.0_291

[crash-2021-07-17_13.41.54-client.txt](https://github.com/Spudstak/Dimensions-Dungeoneering/files/6834673/crash-2021-07-17_13.41.54-client.txt)

**Comment by Spudstak** [comment]
Hmmm, not much I can do with this issue until ITLT fixes it, as I haven't be able to experience it myself. Might have something to do with your java version so try updating that if you can. I'll leave this issue open until ITLT patches it, but if you continue to experience this issue just remove the mod as ITLT doesn't add any content to the pack.

**Comment by Spudstak** [comment]
Fixed in V0.17
