### ISSUE TITLE
Weather causes extreme performance loss

### ISSUE THREAD

**Issue by ZeroHearts** [Spudstak/Dimensions-Dungeoneering#4]
I run MC with at least 10GB of RAM on a system with 32, if going above 10GB MC yells at me for being too much. However, when any weather happens, especially when it snows, it tends to cause extreme FPS drops. Also when it snows it seems like it will coat an entire are around where I am in snow even if part of those biomes don't deal with snow. 
Screenshot included: https://gyazo.com/9f2514a1f5c49dedb1ff93997fa9492c

**Comment by Spudstak** [comment]
Should be Fixed in V0.17 as this was most likely due to the BetterWeather mod which has been removed now. If you experience this again please reopen this issue!
