### ISSUE TITLE
Biomes don't blend naturally

### ISSUE THREAD

**Issue by ZeroHearts** [Spudstak/Dimensions-Dungeoneering#5]
This one is less of something that breaks the game and more of just a bit irritating, biomes can sometimes be just based in chunks and will cut into one another randomly and jaggedly. It makes finding a suitable biome for some difficult as they may be small due to overlapping.

Screenshot included: https://gyazo.com/2856b9198aed5006a506a4d5a5777fce

**Comment by Spudstak** [comment]
Should be Fixed in V0.17 as this was most likely due to the BetterWeather mod which has been removed now. If you experience this again please reopen this issue!
