### ISSUE TITLE
Creative crash

### ISSUE THREAD

**Issue by Zack7292** [Spudstak/Dimensions-Dungeoneering#7]
When going in creative and scrolling to the 14th page of items, the game crashes
[crash-2022-04-17_13.11.25-client.txt](https://github.com/Spudstak/Dimensions-Dungeoneering/files/8502093/crash-2022-04-17_13.11.25-client.txt)

**Comment by Spudstak** [comment]
This is a known issue and it will be fixed in the next update. It's being caused by the Oculus mod.

**Comment by Spudstak** [comment]
Fixed in version 0.20.
